blank_issues_enabled: true
contact_links:
  - name: EspChat.com官方网站
    url: http://62.234.36.202/
    about: 激活设备、配置AI角色
  - name: 聊天机器人配置说明书
    url: https://ccnphfhqs21z.feishu.cn/wiki/F5krwD16viZoF0kKkvDcrZNYnhb
    about: 开发文档、硬件制作、烧录教程、FAQ